package com.cheetah.racer.router.dsl;

import com.cheetah.racer.model.RacerMessage;
import com.cheetah.racer.router.RouteDecision;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Unit tests for {@link RacerFunctionalRouter}.
 */
@ExtendWith(MockitoExtension.class)
class RacerFunctionalRouterTest {

    @Mock
    RouteContext ctx;

    private static RacerMessage msg(String type) {
        return RacerMessage.builder()
                .id("msg-1")
                .channel("orders")
                .payload("{\"type\":\"" + type + "\"}")
                .sender("checkout-service")
                .build();
    }

    // ── evaluate: first match wins ────────────────────────────────────────

    @Test
    void evaluate_firstMatchWins() {
        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("test-router")
                .route(RoutePredicates.fieldEquals("type", "SMS"), RouteHandlers.forward("sms"))
                .route(RoutePredicates.fieldEquals("type", "EMAIL"), RouteHandlers.forward("email"))
                .route(RoutePredicates.any(), RouteHandlers.drop())
                .build();

        RouteDecision result = router.evaluate(msg("EMAIL"), ctx);

        assertThat(result).isEqualTo(RouteDecision.FORWARDED);
    }

    // ── evaluate: no match returns PASS ───────────────────────────────────

    @Test
    void evaluate_noMatch_returnsPASS() {
        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("test-router")
                .route(RoutePredicates.fieldEquals("type", "SMS"), RouteHandlers.forward("sms"))
                .build();

        RouteDecision result = router.evaluate(msg("EMAIL"), ctx);

        assertThat(result).isEqualTo(RouteDecision.PASS);
    }

    // ── evaluate: defaultRoute catches unmatched ──────────────────────────

    @Test
    void evaluate_defaultRoute_catchesUnmatched() {
        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("test-router")
                .route(RoutePredicates.fieldEquals("type", "SMS"), RouteHandlers.forward("sms"))
                .defaultRoute(RouteHandlers.dropToDlq())
                .build();

        RouteDecision result = router.evaluate(msg("EMAIL"), ctx);

        assertThat(result).isEqualTo(RouteDecision.DROPPED_TO_DLQ);
    }

    // ── evaluate: predicate exception skips and continues ─────────────────

    @Test
    void evaluate_predicateException_skipsAndContinues() {
        RoutePredicate throwing = msg -> { throw new RuntimeException("boom"); };

        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("test-router")
                .route(throwing, RouteHandlers.forward("bad"))
                .route(RoutePredicates.fieldEquals("type", "EMAIL"), RouteHandlers.forward("email"))
                .build();

        RouteDecision result = router.evaluate(msg("EMAIL"), ctx);

        assertThat(result).isEqualTo(RouteDecision.FORWARDED);
    }

    // ── builder: immutable entries ────────────────────────────────────────

    @Test
    void builder_producesImmutableEntries() {
        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("test-router")
                .route(RoutePredicates.any(), RouteHandlers.drop())
                .build();

        List<FunctionalRouteEntry> entries = router.entries();

        assertThatThrownBy(() -> entries.add(new FunctionalRouteEntry(RoutePredicates.any(), RouteHandlers.drop())))
                .isInstanceOf(UnsupportedOperationException.class);
    }

    // ── builder: name is preserved ────────────────────────────────────────

    @Test
    void builder_nameIsPreserved() {
        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("my-router")
                .build();

        assertThat(router.getName()).isEqualTo("my-router");
    }

    // ── builder: auto-generated name ──────────────────────────────────────

    @Test
    void builder_autoGeneratedName() {
        RacerFunctionalRouter router = RacerFunctionalRouter.builder().build();

        assertThat(router.getName()).startsWith("functional-router-");
    }

    // ── entries preserve declaration order ─────────────────────────────────

    @Test
    void entries_preserveDeclarationOrder() {
        RouteHandler h1 = RouteHandlers.forward("a");
        RouteHandler h2 = RouteHandlers.forward("b");
        RouteHandler h3 = RouteHandlers.drop();

        RacerFunctionalRouter router = RacerFunctionalRouter.builder()
                .name("order-test")
                .route(RoutePredicates.fieldEquals("type", "A"), h1)
                .route(RoutePredicates.fieldEquals("type", "B"), h2)
                .route(RoutePredicates.any(), h3)
                .build();

        List<FunctionalRouteEntry> entries = router.entries();

        assertThat(entries).hasSize(3);
        assertThat(entries.get(0).handler()).isSameAs(h1);
        assertThat(entries.get(1).handler()).isSameAs(h2);
        assertThat(entries.get(2).handler()).isSameAs(h3);
    }
}
